"""D1–D9 event product with concrete stores and an explicit input time model.

Inputs may change independently at t0 + k*input_step_ms (default 100 ms).
Between these instants they are held. Both programs' deadlines are additional
events, never rounded to the input grid. A tie applies the new input first.

Bounded merging retains time and all concrete stores. Unbounded merging only
rebases interpreter-owned timers when neither program reads the clock;
program-visible values are never saturated or discarded. Catalog-proved constant
integer comparisons may discharge clock dependence; otherwise absolute time is
retained and resource exhaustion is INCONCLUSIVE.
"""
from __future__ import annotations

from collections import deque
from dataclasses import dataclass
import itertools
import math
import time

from explorer.verification.input_model import validate_domains
from explorer.runtime.interp import Unsupported
from explorer.verification.observation import actions_observation
from explorer.verification.state_key import freeze_state as freeze
from explorer.verification.product import Divergence, ProductResult, check_supported_pair
from explorer.runtime.runner import TerminalRunner
from explorer.verification.time_events import silent_deadline, crossed_input_grid


def unwrap(runner):
    while hasattr(runner, "inner"):
        runner = runner.inner
    return runner


def reads_clock(runner, *, catalog_ranges=False):
    from explorer.runtime.expr import ClockRef
    from explorer.runtime.joi_parser import CallExpr
    from explorer.runtime.expr import canonical_key

    model = None
    if catalog_ranges:
        from explorer.verification.service_model import CatalogRunner
        from explorer.runtime.runner import DoneLatch
        from explorer.runtime.ir_step import IrRunner
        from explorer.runtime.oneshot import OneShotRunner
        from explorer.runtime.pause import PauseRunner
        current = runner
        while type(current) in (TerminalRunner, DoneLatch, CatalogRunner):
            if type(current) is CatalogRunner:
                model = current.model
            current = current.inner
        # Unknown wrappers/subclasses may observe time outside the stored AST.
        if type(current) not in (IrRunner, OneShotRunner, PauseRunner):
            model = None
    from explorer.verification.range_analysis import constant_integer_comparison

    def walk(value):
        if model is not None and constant_integer_comparison(value, model.clock_integer_range) is not None:
            return False  # The whole read-only comparison is independent of time.
        if str(getattr(value, "key", "")).startswith("clock."):
            return True
        if isinstance(value, ClockRef):
            return True
        if isinstance(value, CallExpr) and canonical_key(value.service, value.method)[0] == "clock":
            return True
        if isinstance(value, tuple) and len(value) > 1 and value[0] == "read" and str(value[1]).startswith("clock."):
            return True
        if isinstance(value, dict):
            return any(walk(v) for v in value.values())
        if isinstance(value, (list, tuple)):
            return any(walk(v) for v in value)
        if hasattr(value, "__dict__"):
            return walk(vars(value))
        return False
    inner = unwrap(runner)
    return walk(inner.prog.ins if hasattr(inner, "prog") else inner.stmts)


def internal_timers(runner):
    inner = unwrap(runner)
    if hasattr(inner, "prog"):
        # Only registers generated by the IR compiler, never user data.
        names = set()
        for pc, ins in enumerate(inner.prog.ins):
            if ins.kind == "DELAY":
                names.add(f"d{pc}")
            elif ins.kind == "WAIT":
                names.update((f"s{pc}", f"t{pc}"))
            elif ins.kind == "TOP":
                names.add(f"c{ins.idx}")
        return names
    return {"__dstart", "__next_run"}


def next_time(runner_a, runner_b, av, bv, now, t0, input_step_ms, clock_sensitive=False):
    # Neither runner can observe any intermediate input. At the returned event
    # the caller must refresh ALL inputs if even one input-grid point was crossed.
    quiet = silent_deadline(runner_a, runner_b, av, bv, now)
    if quiet is not None:
        return quiet
    grid = t0 + ((now - t0) // input_step_ms + 1) * input_step_ms
    wakes = [r.next_wakeup_ms(v, now, input_step_ms)
             for r, v in ((runner_a, av), (runner_b, bv))]
    if all(w is None for w in wakes):
        return None
    for wake in wakes:
        if wake is not None and (not isinstance(wake, int) or wake <= now):
            raise Unsupported(f"non-progressing or non-integral deadline: {wake}")
    clock_events = [((now // 1000) + 1) * 1000] if clock_sensitive else []
    return min([grid] + clock_events + [w for w in wakes if w is not None])


@dataclass
class Node:
    av: dict
    ag: dict
    bv: dict
    bg: dict
    now: int
    held: dict
    parent: int | None
    dwell: int
    depth: int
    initial_gv: dict


def timed_product(runner_a, runner_b, **kwargs):
    """Binding observation sets of prepared runners apply to every path below."""
    from explorer.verification.observation import observation_scope
    with observation_scope(runner_a, runner_b):
        return _timed_product(runner_a, runner_b, **kwargs)


def _timed_product(runner_a, runner_b, *, input_domains=None,
                  input_step_ms=100, horizon_ms=None, initial_gv_domains=None,
                  t0_ms=2_419_200_000, max_states=400_000,
                  max_transitions=2_000_000, max_input_combinations=100_000,
                  smt_timeout_ms=1000, smt_total_timeout_ms=10000, smt_max_queries=10000,
                  verification_mode='auto'):
    if verification_mode == 'relational':
        from explorer.verification.relational import relational_product
        return relational_product(runner_a, runner_b, input_domains=input_domains,
            horizon_ms=horizon_ms, initial_gv_domains=initial_gv_domains,
            input_step_ms=input_step_ms, t0_ms=t0_ms, max_states=max_states,
            max_transitions=max_transitions, max_input_combinations=max_input_combinations)
    if verification_mode != 'auto':
        raise ValueError('unknown verification_mode: ' + str(verification_mode))
    if not isinstance(input_step_ms, int) or isinstance(input_step_ms, bool) or input_step_ms <= 0:
        raise ValueError("input_step_ms must be a positive integer")
    if type(t0_ms) is not int:
        raise ValueError("t0_ms must be an integer")
    if horizon_ms is not None and (type(horizon_ms) is not int or horizon_ms < 0):
        raise ValueError("horizon_ms must be a nonnegative integer")
    if min(max_states, max_transitions, max_input_combinations) <= 0:
        raise ValueError("resource caps must be positive")
    from explorer.verification.service_model import runner_input_domains
    automatic_inputs = input_domains is None
    if horizon_ms is None and not initial_gv_domains:
        from explorer.verification.relational_analysis import analyze
        try:
            analyze(runner_a, runner_b)
        except Unsupported:
            pass
        else:
            from explorer.verification.relational import relational_product
            return relational_product(runner_a, runner_b, input_domains=input_domains,
                horizon_ms=None, input_step_ms=input_step_ms, t0_ms=t0_ms,
                max_states=max_states, max_transitions=max_transitions,
                max_input_combinations=max_input_combinations)
    if automatic_inputs and not initial_gv_domains:
        from explorer.verification.smt import smt_product
        result = smt_product(runner_a, runner_b, horizon_ms=horizon_ms,
            input_step_ms=input_step_ms, t0_ms=t0_ms, max_states=max_states,
            max_transitions=max_transitions, max_input_combinations=max_input_combinations,
            smt_timeout_ms=smt_timeout_ms, smt_total_timeout_ms=smt_total_timeout_ms,
            smt_max_queries=smt_max_queries)
        if result is not None:
            return result
    try:
        input_domains = runner_input_domains(runner_a, runner_b, input_domains)
    except Unsupported:
        if input_domains is None and not initial_gv_domains:
            from explorer.verification.symbolic import symbolic_product
            symbolic = symbolic_product(runner_a, runner_b,
                horizon_ms=horizon_ms, input_step_ms=input_step_ms, t0_ms=t0_ms,
                max_states=max_states, max_transitions=max_transitions,
                max_input_combinations=max_input_combinations)
            if symbolic is not None:
                return symbolic
        raise
    axes = check_supported_pair(runner_a, runner_b, input_domains=input_domains)
    for runner in (runner_a, runner_b):
        if not hasattr(runner, "next_wakeup_ms"):
            raise Unsupported("timed search needs a scheduled runner (prepare_pair, PauseRunner or OneShotRunner)")
        inner = unwrap(runner)
        if getattr(inner, "repeat", False) and getattr(inner, "period_ms", None) is None:
            raise Unsupported("repeating timed runner requires an explicit completion-relative period")
    domains = axes.cells if input_domains is None else input_domains
    validate_domains(domains, required=axes.cells)
    from explorer.verification.input_coverage import initial_domains
    initial_gv_domains = initial_domains(axes, initial_gv_domains)
    started = time.perf_counter()
    result = ProductResult("EQUIV", bounded_horizon_ms=horizon_ms,
                           input_step_ms=input_step_ms)
    result.notes.append("contract-v1: input grid + exact deadlines; concrete state BFS")
    result.notes.append("silent-time-v1: input-blind sleeps elided; latest grid inputs fully expanded")
    result.notes.append("input domain families: " + repr(axes.input_families)
                        if input_domains is None else "explicit external input domains (no value reduction)")

    def incomplete(reason):
        result.verdict, result.closed = "UNKNOWN", False
        result.notes.append(reason)
        result.seconds = time.perf_counter() - started
        return result

    keys = sorted(domains)
    init_keys = sorted(initial_gv_domains)
    count = math.prod(len(domains[k]) for k in keys)
    init_count = math.prod(len(initial_gv_domains[k]) for k in init_keys)
    if count > max_input_combinations or count * init_count > max_transitions:
        if automatic_inputs and not initial_gv_domains:
            from explorer.verification.symbolic import symbolic_product
            symbolic = symbolic_product(runner_a, runner_b,
                horizon_ms=horizon_ms, input_step_ms=input_step_ms, t0_ms=t0_ms,
                max_states=max_states, max_transitions=max_transitions,
                max_input_combinations=max_input_combinations)
            if symbolic is not None:
                return symbolic
        return incomplete("input/initial-state combination cap reached")
    combos = [dict(zip(keys, vals)) for vals in itertools.product(*(domains[k] for k in keys))]
    initial = [{k: v for k, v in zip(init_keys, vals) if v is not None}
               for vals in itertools.product(*(initial_gv_domains[k] for k in init_keys))]
    a, b = TerminalRunner(runner_a), TerminalRunner(runner_b)
    clock_sensitive = reads_clock(a, catalog_ranges=True) or reads_clock(b, catalog_ranges=True)
    if not clock_sensitive and (reads_clock(a) or reads_clock(b)):
        result.notes.append('catalog-range-v1: every clock read is inside a proved constant integer comparison; original programs executed unchanged')
    absolute_time = horizon_ms is not None or clock_sensitive
    timer_a, timer_b = internal_timers(a), internal_timers(b)
    external_gv = {k[4:] for k in keys if k.startswith("@gv:")}
    nodes, seen, queue = [], set(), deque()

    def split(inputs):
        return ({k: v for k, v in inputs.items() if not k.startswith("@gv:")},
                {k[4:]: v for k, v in inputs.items() if k.startswith("@gv:")})

    def own(gv):
        return {k: v for k, v in gv.items() if k not in external_gv}

    def store_key(values, timers, now):
        if absolute_time:
            return freeze(values)
        return freeze({k: (("age-ms", now - round(v * 1000))
                            if k in timers and v is not None else v)
                       for k, v in values.items()})

    def node_key(node):
        return (store_key(node.av, timer_a, node.now), freeze(node.ag),
                store_key(node.bv, timer_b, node.now), freeze(node.bg),
                node.now if absolute_time else (node.now - t0_ms) % input_step_ms,
                freeze(node.held))

    def path(parent):
        out = []
        while parent is not None:
            node = nodes[parent]
            out.append((node.held, node.dwell))
            parent = node.parent
        return list(reversed(out))

    def transition(av, ag, bv, bg, now, inputs, parent, dwell, depth):
        if result.n_steps // 2 >= max_transitions:
            return incomplete("transition cap reached")
        world, external = split(inputs)
        ra = a.step(av, {**ag, **external}, world, now, first_tick=parent is None)
        rb = b.step(bv, {**bg, **external}, world, now, first_tick=parent is None)
        result.n_steps += 2
        oa, ob = actions_observation(ra.actions), actions_observation(rb.actions)
        initial_gv = dict(ag) if parent is None else nodes[parent].initial_gv
        if oa != ob:
            result.verdict = "DIVERGE"
            result.divergences.append(Divergence(depth, dict(inputs), dwell, oa, ob,
                                                path(parent), initial_gv, t0_ms, input_step_ms))
            result.seconds = time.perf_counter() - started
            return result
        if ra.terminated and rb.terminated:
            return None
        node = Node(ra.vars, own(ra.gv), rb.vars, own(rb.gv), now,
                    dict(inputs), parent, dwell, depth, initial_gv)
        key = node_key(node)
        if key not in seen:
            if len(seen) >= max_states:
                return incomplete("state cap reached")
            seen.add(key)
            queue.append(len(nodes))
            nodes.append(node)
            result.n_states = len(seen)
        return None

    def constant_witness(node, parent):
        """A budgeted concrete path, never a universal successor or certificate.

        From each initial world, follow up to 2048 actual suspension events.
        Later BFS nodes get only one probe. Kept input makes sustained/edge wait
        registers stationary between their own deadlines, as well as sleeps.
        """
        if clock_sensitive:
            return None
        probe = silent_deadline(a, b, node.av, node.bv, node.now, held_waits=True)
        if probe is None or silent_deadline(a, b, node.av, node.bv, node.now) is not None:
            return None
        av, ag, bv, bg, now = node.av, node.ag, node.bv, node.bg, node.now
        history, visited = [], set()
        world, external = split(node.held)
        limit = min(2048, max_states) if node.parent is None else 1
        for _ in range(limit):
            if probe is None or (horizon_ms is not None and probe > t0_ms + horizon_ms):
                break
            if result.n_steps // 2 >= max_transitions:
                return incomplete('transition cap reached')
            ra = a.step(av, {**ag, **external}, world, probe)
            rb = b.step(bv, {**bg, **external}, world, probe)
            result.n_steps += 2
            oa, ob = actions_observation(ra.actions), actions_observation(rb.actions)
            if oa != ob:
                from explorer.verification.product import replay_divergence
                dv = Divergence(node.depth + len(history) + 1, dict(node.held), probe - now,
                                oa, ob, path(parent) + history, node.initial_gv, t0_ms, input_step_ms)
                if replay_divergence(runner_a, runner_b, dv).confirmed:
                    result.verdict = 'DIVERGE'
                    result.divergences.append(dv)
                    result.notes.append('constant-input suspension witness independently replayed')
                    result.seconds = time.perf_counter() - started
                    return result
                break
            history.append((dict(node.held), probe - now))
            av, ag, bv, bg, now = ra.vars, own(ra.gv), rb.vars, own(rb.gv), probe
            key = (store_key(av, timer_a, now), freeze(ag), store_key(bv, timer_b, now),
                   freeze(bg), (now - t0_ms) % input_step_ms)
            if key in visited: break
            visited.add(key)
            probe = silent_deadline(a, b, av, bv, now, held_waits=True)
        return None

    for inputs in combos:
        for gv in initial:
            stopped = transition({}, gv, {}, gv, t0_ms, inputs, None, 0, 0)
            if stopped is not None:
                return stopped
    while queue:
        parent = queue.popleft()
        node = nodes[parent]
        stopped = constant_witness(node, parent)
        if stopped is not None:
            return stopped
        now = next_time(a, b, node.av, node.bv, node.now, t0_ms, input_step_ms, clock_sensitive)
        if now is None or (horizon_ms is not None and now > t0_ms + horizon_ms):
            continue
        choices = combos if crossed_input_grid(node.now, now, t0_ms, input_step_ms) else [node.held]
        for inputs in choices:
            stopped = transition(node.av, node.ag, node.bv, node.bg, now,
                                 inputs, parent, now - node.now, node.depth + 1)
            if stopped is not None:
                return stopped
    result.seconds = time.perf_counter() - started
    return result
