kind: automation
key: C08_022
automation:
  alias: C08_022
  mode: single
  triggers:
  - trigger: numeric_state
    entity_id: sensor.main_window_current_position
    above: 0
  conditions: []
  actions:
  - action: media_player.speak
    target:
      entity_id:
      - media_player.main_speaker
      - media_player.bedroom_speaker
    data:
      Text: The window is open
