kind: automation
key: C08_029
automation:
  alias: C08_029
  mode: single
  triggers:
  - trigger: numeric_state
    entity_id: sensor.up_light_current_brightness
    above: 0
  conditions: []
  actions:
  - action: light.move_to_brightness
    target:
      entity_id:
      - light.down_light
    data:
      Brightness: 100
      Rate: 0
