kind: automation
key: C08_028
automation:
  alias: C08_028
  mode: single
  triggers:
  - trigger: numeric_state
    entity_id: sensor.light_sens_brightness
    below: 200
  conditions: []
  actions:
  - action: light.move_to_brightness
    target:
      entity_id:
      - light.lr_light
      - light.out_light
    data:
      Brightness: 100
      Rate: 0
