kind: automation
key: C08_039
automation:
  alias: C08_039
  mode: single
  triggers:
  - trigger: state
    entity_id: binary_sensor.y_mot_motion
    to: 'on'
  conditions: []
  actions:
  - action: siren.set_siren_mode
    target:
      entity_id:
      - siren.y_siren
    data:
      Mode: police
