kind: automation
key: C08_018
automation:
  alias: C08_018
  mode: single
  triggers:
  - trigger: template
    value_template: '{{ (states(''sensor.main_humidity_sensor_humidity'')|float <= 30 or states(''sensor.bedroom_humidity_sensor_humidity'')|float
      <= 30) }}'
  conditions: []
  actions:
  - action: humidifier.turn_on
    target:
      entity_id:
      - humidifier.main_humidifier
      - humidifier.bedroom_humidifier
