kind: automation
key: C08_023
automation:
  alias: C08_023
  mode: single
  triggers:
  - trigger: template
    value_template: '{{ (states(''sensor.living_light_sensor_brightness'')|float < 100 or
      states(''sensor.bedroom_light_sensor_brightness'')|float < 100) }}'
  conditions: []
  actions:
  - action: light.move_to_brightness
    target:
      entity_id:
      - light.living_light
      - light.bedroom_light
    data:
      Brightness: 100
      Rate: 0
