kind: automation
key: C08_036
automation:
  alias: C08_036
  mode: single
  triggers:
  - trigger: state
    entity_id: binary_sensor.ent_motion_motion
    to: 'on'
  conditions: []
  actions:
  - action: light.move_to_brightness
    target:
      entity_id:
      - light.ent_light
    data:
      Brightness: 100
      Rate: 0
  - delay:
      seconds: 3
  - action: light.turn_off
    target:
      entity_id:
      - light.ent_light
