kind: automation
key: C08_038
automation:
  alias: C08_038
  mode: single
  triggers:
  - trigger: state
    entity_id: binary_sensor.k_leak_leakage
    to: 'on'
  conditions: []
  actions:
  - action: camera.start_recording
    target:
      entity_id:
      - camera.k_cam
