kind: automation
key: C08_031
automation:
  alias: C08_031
  mode: single
  triggers:
  - trigger: state
    entity_id: sensor.r_button_button
    to: pushed
  conditions: []
  actions:
  - action: vacuum.set_robot_vacuum_cleaner_cleaning_mode
    target:
      entity_id:
      - vacuum.even_robot_1
      - vacuum.even_robot_2
    data:
      Mode: auto
