kind: automation
key: C08_034
automation:
  alias: C08_034
  mode: single
  triggers:
  - trigger: state
    entity_id: sensor.home_weather_provider_weather
    to: rain
  conditions: []
  actions:
  - action: cover.close_cover
    target:
      entity_id:
      - cover.win_1
      - cover.win_2
  - action: lock.lock
    target:
      entity_id:
      - lock.door_lock_1
      - lock.door_lock_2
