kind: automation
key: C08_030
automation:
  alias: C08_030
  mode: single
  triggers:
  - trigger: state
    entity_id: sensor.l_button_button
    to: pushed
  conditions: []
  actions:
  - action: light.move_to_level
    target:
      entity_id:
      - light.odd_light_1
      - light.odd_light_2
    data:
      Level: 100
      Rate: 0
