kind: automation
key: C08_040
automation:
  alias: C08_040
  mode: single
  triggers:
  - trigger: state
    entity_id: sensor.lr_mb_button2
    to: pushed
  conditions: []
  actions:
  - action: cover.open_cover
    target:
      entity_id:
      - cover.lr_win_1
      - cover.lr_win_2
