kind: automation
key: C08_033
automation:
  alias: C08_033
  mode: single
  triggers:
  - trigger: state
    entity_id: sensor.stop_button_button
    to: pushed
  conditions: []
  actions:
  - action: charger.turn_off
    target:
      entity_id:
      - charger.even_charger
  - action: light.turn_off
    target:
      entity_id:
      - light.even_light
