kind: automation
key: C08_021
automation:
  alias: C08_021
  mode: single
  triggers:
  - trigger: template
    value_template: '{{ (states(''sensor.main_humidity_sensor_humidity'')|float < 50 or states(''sensor.bedroom_humidity_sensor_humidity'')|float
      < 50) }}'
  conditions: []
  actions:
  - action: dehumidifier.set_dehumidifier_mode
    target:
      entity_id:
      - dehumidifier.main_dehumidifier
      - dehumidifier.bathroom_dehumidifier
    data:
      Mode: drying
