kind: automation
key: C08_027
automation:
  alias: C08_027
  mode: single
  triggers:
  - trigger: template
    value_template: '{{ states(''sensor.g1_humidity_humidity'')|float >= 50 }}'
  conditions: []
  actions:
  - action: dehumidifier.set_dehumidifier_mode
    target:
      entity_id:
      - dehumidifier.g1_dehum_1
      - dehumidifier.g1_dehum_2
    data:
      Mode: drying
