kind: automation
key: C08_037
automation:
  alias: C08_037
  mode: single
  triggers:
  - trigger: template
    value_template: '{{ (states(''sensor.light_s_brightness'')|float < 50 or states(''sensor.indoor_light_s_brightness'')|float
      < 50) }}'
  conditions: []
  actions:
  - action: cover.open_cover
    target:
      entity_id:
      - cover.p_shade_1
      - cover.p_shade_2
