kind: automation
key: C08_020
automation:
  alias: C08_020
  mode: single
  triggers:
  - trigger: template
    value_template: '{{ (states(''sensor.main_sound_sensor_sound'')|float > 30 or states(''sensor.bedroom_sound_sensor_sound'')|float
      > 30) }}'
  conditions: []
  actions:
  - action: fan.set_air_purifier_mode
    target:
      entity_id:
      - fan.main_air_purifier
      - fan.bedroom_air_purifier
    data:
      Mode: sleep
