kind: automation
key: C13_007
automation:
  alias: C13_007
  mode: single
  triggers:
  - trigger: time_pattern
    hours: /1
  conditions: []
  actions:
  - if:
    - condition: template
      value_template: '{{ ((states(''counter.c13_007_n'')|int % 2) == 0) }}'
    then:
    - action: climate.set_target_temperature
      target:
        entity_id:
        - climate.mr_ac
      data:
        Temperature: 25
    else:
    - action: climate.set_target_temperature
      target:
        entity_id:
        - climate.mr_ac
      data:
        Temperature: 20
  - action: counter.increment
    target:
      entity_id: counter.c13_007_n
helpers:
  counter:
    c13_007_n:
      initial: 0
