kind: automation
key: C13_003
automation:
  alias: C13_003
  mode: single
  triggers:
  - trigger: time_pattern
    minutes: /10
  conditions: []
  actions:
  - if:
    - condition: template
      value_template: '{{ ((states(''counter.c13_003_n'')|int % 2) == 0) }}'
    then:
    - action: cover.open_cover
      target:
        entity_id:
        - cover.main_window
        - cover.bedroom_window
    else:
    - action: cover.close_cover
      target:
        entity_id:
        - cover.main_window
        - cover.bedroom_window
  - action: counter.increment
    target:
      entity_id: counter.c13_003_n
helpers:
  counter:
    c13_003_n:
      initial: 0
