kind: automation
key: C14_001
automation:
  alias: C14_001
  mode: single
  triggers:
  - trigger: state
    entity_id: sensor.hall_mb_button1
    to: pushed
  conditions: []
  actions:
  - action: light.move_to_brightness
    target:
      entity_id:
      - light.hall_light
    data:
      Brightness: min({{ states('sensor.hall_light_current_brightness') }} + 10, 100)
      Rate: 0
    response_variable: Light
