kind: automation
key: C14_004
automation:
  alias: C14_004
  mode: single
  triggers:
  - trigger: template
    value_template: '{{ (is_state(''binary_sensor.entrance_motion_motion'', ''on'') or is_state(''binary_sensor.garage_motion_motion'',
      ''on'')) }}'
  conditions: []
  actions:
  - action: light.move_to_brightness
    target:
      entity_id:
      - light.living_light
    data:
      Brightness: min({{ states('sensor.living_light_current_brightness') }} + 10, 100)
      Rate: 0
  - if:
    - condition: template
      value_template: '{{ states(''sensor.living_light_current_brightness'')|float >= 100
        }}'
    then:
    - stop: break
