kind: automation
key: C14_003
automation:
  alias: C14_003
  mode: single
  triggers:
  - trigger: state
    entity_id: sensor.lr_mb_button4
    to: pushed
  conditions: []
  actions:
  - if:
    - condition: template
      value_template: '{{ ((states(''counter.c14_003_n'')|int % 3) == 0) }}'
    then:
    - action: light.move_to_brightness
      target:
        entity_id:
        - light.lr_light_1
        - light.lr_light_2
      data:
        Brightness: 25
        Rate: 0
    else:
    - if:
      - condition: template
        value_template: '{{ ((states(''counter.c14_003_n'')|int % 3) == 1) }}'
      then:
      - action: light.move_to_brightness
        target:
          entity_id:
          - light.lr_light_1
          - light.lr_light_2
        data:
          Brightness: 50
          Rate: 0
      else:
      - action: light.move_to_brightness
        target:
          entity_id:
          - light.lr_light_1
          - light.lr_light_2
        data:
          Brightness: 75
          Rate: 0
  - action: counter.increment
    target:
      entity_id: counter.c14_003_n
helpers:
  counter:
    c14_003_n:
      initial: 0
