kind: automation
key: C14_006
automation:
  alias: C14_006
  mode: single
  triggers:
  - trigger: state
    entity_id: sensor.living_room_mb_button4
    to: pushed
  conditions: []
  actions:
  - action: light.move_to_level
    target:
      entity_id:
      - light.living_room_light
    data:
      Level: max({{ states('sensor.living_room_light_current_level') }} - 15, 10)
      Rate: 0
    response_variable: LevelControl.CurrentLevel
