kind: automation
key: C15_020
automation:
  alias: C15_020
  mode: single
  triggers:
  - trigger: time
    at: 00:00:00
  conditions: []
  actions:
  - action: camera.capture_image
    target:
      entity_id:
      - camera.p_cam_1
      - camera.p_cam_2
