kind: automation
key: C15_001
automation:
  alias: C15_001
  mode: single
  triggers:
  - trigger: time
    at: '18:00:00'
  conditions: []
  actions:
  - action: cover.set_cover_position
    target:
      entity_id:
      - cover.wall_blind_1
      - cover.wall_blind_3
    data:
      Level: 50
