kind: automation
key: C15_013
automation:
  alias: C15_013
  mode: single
  triggers:
  - trigger: time
    at: '23:00:00'
  conditions: []
  actions:
  - action: lock.lock
    target:
      entity_id:
      - lock.door_lock_2
      - lock.door_lock_4
