kind: automation
key: C15_021
automation:
  alias: C15_021
  mode: single
  triggers:
  - trigger: time
    at: '23:00:00'
  conditions: []
  actions:
  - action: light.turn_off
    target:
      entity_id:
      - light.odd_f1_light_1
      - light.odd_f1_light_2
