kind: automation
key: C15_014
automation:
  alias: C15_014
  mode: single
  triggers:
  - trigger: time
    at: 07:00:00
  conditions: []
  actions:
  - action: cover.open_cover
    target:
      entity_id:
      - cover.z1_blind_1
      - cover.z1_blind_2
