kind: automation
key: C15_017
automation:
  alias: C15_017
  mode: single
  triggers:
  - trigger: time
    at: 08:00:00
  conditions: []
  actions:
  - action: light.move_to_brightness
    target:
      entity_id:
      - light.main_light
      - light.bedroom_light
    data:
      Brightness: 100
      Rate: 0
