kind: automation
key: C15_016
automation:
  alias: C15_016
  mode: single
  triggers:
  - trigger: time
    at: 09:00:00
  conditions: []
  actions:
  - action: cover.open_cover
    target:
      entity_id:
      - cover.f3_even_blind_1
      - cover.f3_even_blind_2
