kind: automation
key: C15_008
automation:
  alias: C15_008
  mode: single
  triggers:
  - trigger: time
    at: 06:00:00
  conditions:
  - condition: time
    weekday:
    - mon
    - wed
  actions:
  - variables:
      Weather: '{{ states(''sensor.main_weather_weather'') }}'
  - action: media_player.speak
    target:
      entity_id:
      - media_player.living_speaker
      - media_player.bedroom_speaker
    data:
      Text: Today's weather is {{ Weather }}
