kind: automation
key: C15_018
automation:
  alias: C15_018
  mode: single
  triggers:
  - trigger: time
    at: 08:00:00
  conditions: []
  actions:
  - action: fan.turn_on
    target:
      entity_id:
      - fan.high_efficiency_air_purifier
      - fan.low_efficiency_air_purifier
  - action: fan.set_air_purifier_mode
    target:
      entity_id:
      - fan.high_efficiency_air_purifier
      - fan.low_efficiency_air_purifier
    data:
      Mode: auto
