kind: automation
key: C15_004
automation:
  alias: C15_004
  mode: single
  triggers:
  - trigger: time
    at: 07:00:00
  conditions: []
  actions:
  - action: humidifier.set_humidifier_mode
    target:
      entity_id:
      - humidifier.kitchen_humidifier
      - humidifier.dining_humidifier
    data:
      Mode: auto
