kind: automation
key: C15_003
automation:
  alias: C15_003
  mode: single
  triggers:
  - trigger: time
    at: 00:00:00
  conditions: []
  actions:
  - action: lock.lock
    target:
      entity_id:
      - lock.entrance_lock
      - lock.garage_lock
