kind: automation
key: C15_009
automation:
  alias: C15_009
  mode: single
  triggers:
  - trigger: time
    at: '12:00:00'
  conditions: []
  actions:
  - action: menu_provider.get_menu
    target:
      entity_id:
      - menu_provider.main_menu_provider
      - menu_provider.office_menu_provider
    data:
      Command: 오늘 301동식당 점심
    response_variable: GetMenu
  - action: media_player.speak
    target:
      entity_id:
      - media_player.living_speaker
      - media_player.bedroom_speaker
    data:
      Text: '{{ GetMenu }}'
