kind: automation
key: C15_015
automation:
  alias: C15_015
  mode: single
  triggers:
  - trigger: time
    at: 08:00:00
  conditions: []
  actions:
  - action: cover.open_cover
    target:
      entity_id:
      - cover.odd_blind_1
      - cover.odd_blind_2
  - delay:
      hours: 1
  - action: cover.open_cover
    target:
      entity_id:
      - cover.odd_blind_1
      - cover.odd_blind_2
