kind: automation
key: C16_012
automation:
  alias: C16_012
  mode: single
  triggers:
  - trigger: time
    at: '18:00:00'
  conditions: []
  actions:
  - if:
    - condition: template
      value_template: '{{ (states(''sensor.living_room_window_current_position'')|float >
        0 or states(''sensor.bedroom_window_current_position'')|float > 0) }}'
    then:
    - action: cover.close_cover
      target:
        entity_id:
        - cover.living_room_window
        - cover.bedroom_window
