kind: automation
key: C16_002
automation:
  alias: C16_002
  mode: single
  triggers:
  - trigger: time
    at: 08:00:00
  conditions:
  - condition: time
    weekday:
    - mon
  actions:
  - if:
    - condition: template
      value_template: '{{ (states(''sensor.main_door_lock_door_lock_state'') == ''closed''
        and states(''sensor.entrance_lock_door_lock_state'') == ''closed'') }}'
    then:
    - action: media_player.speak
      target:
        entity_id:
        - media_player.living_speaker
        - media_player.bedroom_speaker
      data:
        Text: It is safe
