kind: automation
key: C16_003
automation:
  alias: C16_003
  mode: single
  triggers:
  - trigger: time
    at: '19:00:00'
  conditions: []
  actions:
  - repeat:
      while:
      - condition: time
        before: '22:00:00'
      sequence:
      - if:
        - condition: state
          entity_id: sensor.living_rvc_robot_vacuum_cleaner_cleaning_mode
          state: stop
        then:
        - action: vacuum.set_robot_vacuum_cleaner_cleaning_mode
          target:
            entity_id:
            - vacuum.living_rvc
          data:
            Mode: auto
      - wait_for_trigger:
        - trigger: time_pattern
          minutes: /30
