kind: automation
key: C16_011
automation:
  alias: C16_011
  mode: single
  triggers:
  - trigger: time
    at: '22:00:00'
  conditions: []
  actions:
  - repeat:
      while:
      - condition: time
        before: '23:00:00'
      sequence:
      - if:
        - condition: state
          entity_id: sensor.main_charger_charging_state
          state: fullyCharged
        then:
        - action: charger.turn_off
          target:
            entity_id:
            - charger.main_charger
            - charger.phone_charger
      - wait_for_trigger:
        - trigger: time_pattern
          minutes: /5
