kind: automation
key: C16_006
automation:
  alias: C16_006
  mode: single
  triggers:
  - trigger: time
    at: '18:00:00'
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - if:
    - condition: state
      entity_id: binary_sensor.off_presence_presence
      state: 'off'
    then:
    - action: climate.turn_off
      target:
        entity_id:
        - climate.off_ac_1
        - climate.off_ac_2
    - action: humidifier.turn_off
      target:
        entity_id:
        - humidifier.off_hum_1
        - humidifier.off_hum_2
