kind: automation
key: C16_010
automation:
  alias: C16_010
  mode: single
  triggers:
  - trigger: time
    at: 08:00:00
  conditions: []
  actions:
  - action: media_player.speak
    target:
      entity_id:
      - media_player.main_speaker
      - media_player.bedroom_speaker
    data:
      Text: Get up
  - if:
    - condition: template
      value_template: '{{ states(''sensor.main_window_current_position'')|float == 0 }}'
    then:
    - action: cover.open_cover
      target:
        entity_id:
        - cover.main_window
