kind: automation
key: C16_004
automation:
  alias: C16_004
  mode: single
  triggers:
  - trigger: time
    at: '23:00:00'
  conditions: []
  actions:
  - if:
    - condition: template
      value_template: '{{ (states(''sensor.main_door_lock_door_lock_state'') == ''open'' or
        states(''sensor.entrance_lock_door_lock_state'') == ''open'') }}'
    then:
    - action: media_player.speak
      target:
        entity_id:
        - media_player.living_speaker
        - media_player.bedroom_speaker
      data:
        Text: Check the safe and door lock
