kind: automation
key: C17_011
automation:
  alias: C17_011
  mode: single
  triggers:
  - trigger: state
    entity_id: sensor.p_charge_charging_state
    to: fullyCharged
  conditions: []
  actions:
  - action: media_player.speak
    target:
      entity_id:
      - media_player.p_speaker
    data:
      Text: Charging is complete
