kind: automation
key: C17_003
automation:
  alias: C17_003
  mode: single
  triggers:
  - trigger: time_pattern
    hours: /1
  conditions: []
  actions:
  - action: media_player.volume_set
    target:
      entity_id:
      - media_player.living_speaker
    data:
      Volume: '{{ states(''sensor.living_speaker_volume'') }} + 10'
    response_variable: Speaker.Volume
