kind: automation
key: C17_005
automation:
  alias: C17_005
  mode: single
  triggers:
  - trigger: time_pattern
    minutes: /10
  conditions: []
  actions:
  - if:
    - condition: template
      value_template: '{{ (states(''sensor.living_hum_humidity'')|float >= 50 or states(''sensor.bedroom_hum_humidity'')|float
        >= 50) }}'
    then:
    - action: humidifier.turn_off
      target:
        entity_id:
        - humidifier.living_humidifier
        - humidifier.bedroom_humidifier
    else:
    - if:
      - condition: template
        value_template: '{{ (states(''sensor.living_hum_humidity'')|float <= 20 or states(''sensor.bedroom_hum_humidity'')|float
          <= 20) }}'
      then:
      - action: humidifier.turn_on
        target:
          entity_id:
          - humidifier.living_humidifier
          - humidifier.bedroom_humidifier
      - action: humidifier.set_humidifier_mode
        target:
          entity_id:
          - humidifier.living_humidifier
          - humidifier.bedroom_humidifier
        data:
          Mode: auto
