kind: automation
key: C18_004
automation:
  alias: C18_004
  mode: single
  triggers:
  - trigger: time_pattern
    minutes: /10
  conditions:
  - condition: state
    entity_id: input_boolean.c18_004_done
    state: 'off'
  actions:
  - if:
    - condition: time
      after: '15:00:00'
    then:
    - action: input_boolean.turn_on
      target:
        entity_id: input_boolean.c18_004_done
    - stop: until
  - action: siren.set_siren_mode
    target:
      entity_id:
      - siren.main_siren
      - siren.entrance_siren
    data:
      Mode: emergency
  - delay:
      seconds: 5
  - action: siren.turn_off
    target:
      entity_id:
      - siren.main_siren
      - siren.entrance_siren
helpers:
  input_boolean:
    c18_004_done:
      initial: 'off'
