kind: automation
key: C18_010
automation:
  alias: C18_010
  mode: single
  triggers:
  - trigger: time
    at: 00:00:00
  conditions: []
  actions:
  - action: lock.lock
    target:
      entity_id:
      - lock.entrance_door_lock
      - lock.garage_door_lock
  - repeat:
      while:
      - condition: time
        before: 06:00:00
      sequence:
      - if:
        - condition: numeric_state
          entity_id: sensor.living_light_current_level
          above: 30
        then:
        - action: light.move_to_level
          target:
            entity_id:
            - light.living_light
          data:
            Level: 10
            Rate: 0
      - wait_for_trigger:
        - trigger: time_pattern
          hours: /1
