kind: automation
key: C19_008
automation:
  alias: C19_008
  mode: single
  triggers:
  - trigger: time_pattern
    seconds: /1
  conditions: []
  actions:
  - if:
    - condition: template
      value_template: '{{ states(''sensor.bathroom_humidity_sensor_humidity'')|float >= 75
        }}'
    then:
    - action: switch.turn_on
      target:
        entity_id:
        - switch.bathroom_fan
    else:
    - if:
      - condition: template
        value_template: '{{ states(''sensor.bathroom_humidity_sensor_humidity'')|float <=
          55 }}'
      then:
      - action: switch.turn_off
        target:
          entity_id:
          - switch.bathroom_fan
