kind: automation
key: C19_006
automation:
  alias: C19_006
  mode: single
  triggers:
  - trigger: time_pattern
    seconds: /1
  conditions: []
  actions:
  - if:
    - condition: template
      value_template: '{{ states(''sensor.bedroom_temp_sensor_temperature'')|float >= 26 }}'
    then:
    - action: switch.turn_on
      target:
        entity_id:
        - switch.bedroom_fan
    else:
    - if:
      - condition: template
        value_template: '{{ states(''sensor.bedroom_temp_sensor_temperature'')|float <= 23
          }}'
      then:
      - action: switch.turn_off
        target:
          entity_id:
          - switch.bedroom_fan
