kind: automation
key: C19_003
automation:
  alias: C19_003
  mode: single
  triggers:
  - trigger: time_pattern
    seconds: /1
  conditions: []
  actions:
  - if:
    - condition: template
      value_template: '{{ states(''sensor.living_room_light_sensor_brightness'')|float <=
        200 }}'
    then:
    - action: switch.turn_on
      target:
        entity_id:
        - switch.living_room_lamp
    else:
    - if:
      - condition: template
        value_template: '{{ states(''sensor.living_room_light_sensor_brightness'')|float >=
          500 }}'
      then:
      - action: switch.turn_off
        target:
          entity_id:
          - switch.living_room_lamp
