kind: automation
key: C22_005
automation:
  alias: C22_005
  mode: single
  triggers:
  - trigger: time_pattern
    minutes: /20
  conditions:
  - condition: numeric_state
    entity_id: counter.c22_005_n
    below: 5
  actions:
  - action: media_player.speak
    target:
      entity_id:
      - media_player.living_room_speaker
      - media_player.bedroom_speaker
    data:
      Text: meeting reminder
  - action: counter.increment
    target:
      entity_id: counter.c22_005_n
helpers:
  counter:
    c22_005_n:
      initial: 0
