kind: automation
key: C22_007
automation:
  alias: C22_007
  mode: single
  triggers:
  - trigger: time_pattern
    hours: /1
  conditions:
  - condition: numeric_state
    entity_id: counter.c22_007_n
    below: 5
  actions:
  - action: cover.open_cover
    target:
      entity_id:
      - cover.bedroom_blind
  - action: counter.increment
    target:
      entity_id: counter.c22_007_n
helpers:
  counter:
    c22_007_n:
      initial: 0
