kind: automation
key: C22_010
automation:
  alias: C22_010
  mode: single
  triggers:
  - trigger: time_pattern
    seconds: /20
  conditions:
  - condition: numeric_state
    entity_id: counter.c22_010_n
    below: 8
  actions:
  - action: light.move_to_brightness
    target:
      entity_id:
      - light.kitchen_light
    data:
      Brightness: 100
      Rate: 0
  - action: counter.increment
    target:
      entity_id: counter.c22_010_n
helpers:
  counter:
    c22_010_n:
      initial: 0
