kind: automation
key: C22_008
automation:
  alias: C22_008
  mode: single
  triggers:
  - trigger: time_pattern
    minutes: /15
  conditions:
  - condition: numeric_state
    entity_id: counter.c22_008_n
    below: 4
  actions:
  - action: fan.set_air_purifier_mode
    target:
      entity_id:
      - fan.living_room_air_purifier
      - fan.bedroom_air_purifier
    data:
      Mode: high
  - action: counter.increment
    target:
      entity_id: counter.c22_008_n
helpers:
  counter:
    c22_008_n:
      initial: 0
