kind: automation
key: C22_004
automation:
  alias: C22_004
  mode: single
  triggers:
  - trigger: time_pattern
    minutes: /2
  conditions:
  - condition: numeric_state
    entity_id: counter.c22_004_n
    below: 6
  actions:
  - action: switch.turn_on
    target:
      entity_id:
      - switch.living_room_ac
  - action: counter.increment
    target:
      entity_id: counter.c22_004_n
helpers:
  counter:
    c22_004_n:
      initial: 0
