kind: automation
key: C25_003
automation:
  alias: C25_003
  mode: single
  triggers:
  - trigger: time_pattern
    minutes: /1
  conditions:
  - condition: numeric_state
    entity_id: counter.c25_003_n
    below: 10
  actions:
  - variables:
      v: '{{ states(''sensor.server_temp_temperature'') }}'
  - if:
    - condition: template
      value_template: '{{ (v >= 30) }}'
    then:
    - action: climate.set_air_conditioner_mode
      target:
        entity_id:
        - climate.server_ac
      data:
        Mode: cool
    else:
    - action: climate.set_air_conditioner_mode
      target:
        entity_id:
        - climate.server_ac
      data:
        Mode: auto
  - action: counter.increment
    target:
      entity_id: counter.c25_003_n
helpers:
  counter:
    c25_003_n:
      initial: 0
