kind: automation
key: C25_004
automation:
  alias: C25_004
  mode: single
  triggers:
  - trigger: time_pattern
    minutes: /30
  conditions:
  - condition: numeric_state
    entity_id: counter.c25_004_n
    below: 5
  actions:
  - variables:
      v: '{{ states(''sensor.office_temp_temperature'') }}'
  - if:
    - condition: template
      value_template: '{{ (v >= 26) }}'
    then:
    - action: climate.set_air_conditioner_mode
      target:
        entity_id:
        - climate.office_ac
      data:
        Mode: cool
    else:
    - action: climate.set_air_conditioner_mode
      target:
        entity_id:
        - climate.office_ac
      data:
        Mode: auto
  - action: counter.increment
    target:
      entity_id: counter.c25_004_n
helpers:
  counter:
    c25_004_n:
      initial: 0
