kind: automation
key: C26_006
automation:
  alias: C26_006
  mode: single
  triggers:
  - trigger: state
    entity_id: sensor.home_weather_provider_weather
    to: rain
  conditions: []
  actions:
  - wait_template: '{{ states(''sensor.living_window_current_position'')|float == 0 }}'
    timeout:
      minutes: 3
    continue_on_timeout: true
  - if:
    - condition: template
      value_template: '{{ not wait.completed }}'
    then:
    - action: cover.close_cover
      target:
        entity_id:
        - cover.living_window
    - stop: timeout
